# -*- coding: utf-8 -*-
"""Exemplos_Praticos_RioAraguaia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aynLK9Nw22cvquclUYXnQ3B0wYD4iOJj

# Introdução à API Sentinel-2 — Exemplos práticos (Rio Araguaia)

Este notebook faz parte do **material introdutório** sobre como utilizar a API do SentinelHub, mostrando os **fundamentos** e **exemplos práticos** da utilização desses dados.


| Parte | Conteúdo | O que a turma leva |
|---|---------|--------------------|
| 0 | Setup | Credenciais seguras e token de acesso |
| 1.1–1.7 | **Fundamentos**: bandas, requisição, evalscript, AUTO × FLOAT32, nuvens, resolução, `baixar()` | Entender cada peça antes de usar |
| 1 | Quanto de água o rio perdeu? | Transformar pixels em km² |
| 2 | Limiar interativo (slider) | Entender que "água" é uma decisão |
| 3 | Mapa de mudança cheia × seca (estático + interativo) | Álgebra de mapas / classes, camadas liga/desliga |
| 4 | O pulso do rio: timelapse + gráfico mensal | Série temporal e um GIF para compartilhar |
| 5 | Caça ao fogo: ver através da fumaça + área queimada | Bandas SWIR, NBR, dNBR |
| 6 | Classificação automática (K-means) | Machine learning não supervisionado |
| 7 | Sua cidade | Cada aluno roda na própria região |


Documentação da API: https://documentation.dataspace.copernicus.eu/APIs/SentinelHub/ApiReference.html

Notebooks mais aprofundados: https://github.com/eu-cdse/notebook-samples/tree/main/sentinelhub

## 0. Setup

**Cada participante deve criar a própria conta gratuita**, caso não tenha criado, siga o seguinte [**>>tutorial<<**](https://drive.google.com/file/d/1YJk_gkmpKVIqHIQHDJygRcZIXUODpHoB/view?usp=sharing). No Colab, salve as chaves em **🔑 Secrets** (<u>icone de chave no canto esquerdo</u>) com os nomes
`id` e `secret` (assim ninguém precisa colar as credenciais no código).
"""

# !pip install -q oauthlib requests_oauthlib tifffile folium scikit-learn
import os, io, time, calendar
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import tifffile
from getpass import getpass
from oauthlib.oauth2 import BackendApplicationClient
from requests_oauthlib import OAuth2Session

try:
    from google.colab import userdata
    client_id = userdata.get("id")
    client_secret = userdata.get("secret")
except Exception:
    client_id = os.environ.get("id") or input("client_id: ")
    client_secret = os.environ.get("secret") or getpass("client_secret: ")

TOKEN_URL = "https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token"
PROCESS_URL = "https://sh.dataspace.copernicus.eu/process/v1"

oauth = OAuth2Session(client=BackendApplicationClient(client_id=client_id))

def garantir_token():
    """O token do CDSE expira em poucos minutos; renova automaticamente."""
    if not oauth.token or oauth.token.get("expires_at", 0) < time.time() + 60:
        oauth.fetch_token(token_url=TOKEN_URL, client_secret=client_secret, include_client_id=True)

garantir_token()
print(f"Token OK — válido por {oauth.token['expires_in']} segundos")

"""# Parte 1 — Fundamentos: como a API funciona

Antes dos exemplos, vamos entender as peças. Toda imagem que baixamos segue este caminho:

```
(1) Seu código ── client_id + client_secret ──► Servidor de identidade ──► devolve um TOKEN (vale ~30 min)

(2) Seu código ── TOKEN + requisição JSON ──► Process API
                   │  • ONDE?   bbox / polígono
                   │  • QUANDO? período + filtro de nuvem
                   │  • O QUÊ?  evalscript (a "receita" de cada pixel)
                   ▼
    Process API: acha as cenas ► roda o evalscript em CADA pixel ► devolve a imagem (TIFF/PNG)
```

A célula de setup acima já fez o passo (1). Agora vamos fazer o passo (2) na mão.

## 1.1 As bandas do Sentinel-2

O satélite "enxerga" em 13 faixas de luz (bandas), várias invisíveis ao olho humano.
No produto **L2A** os valores já vêm como **refletância** (de 0 a 1: quanto da luz a superfície reflete).

| Banda | Nome | Resolução | Para que serve |
|-------|------|-----------|----------------|
| B01 | aerossol costeiro | 60 m | aerossóis, águas costeiras |
| B02 | Azul | 10 m | cor verdadeira, água |
| B03 | Verde | 10 m | cor verdadeira, NDWI |
| B04 | Vermelho | 10 m | cor verdadeira, NDVI (vegetação absorve vermelho) |
| B05 | Borda vermelho 704nm| 20 m | borda do vermelho: clorofila e saúde da vegetação |
| B06 | Borda vermelho 740.5 nm| 20 m | borda do vermelho: clorofila e saúde da vegetação |
| B07 | Borda vermelho 782.8 nm| 20 m | borda do vermelho: clorofila e saúde da vegetação |
| B08 | Infravermelho próximo (NIR) | 10 m | vegetação reflete MUITO; água quase nada |
| B8A | NIR estreito | 20 m | vegetação, composições SWIR |
| B09 | Vapor d'agua | 60 m | detectar umidade, monitorar massas de ar |
| B10 | Cirrus | 60 m | detecção de nuvens (**só no L1C** — não existe no L2A) |
| B11 | Infravermelho de ondas curtas (SWIR 1) | 20 m | umidade do solo/vegetação |
| B12 | SWIR 2 | 20 m | fogo ativo, queimadas, atravessa fumaça |
| SCL | Classificação da cena | 20 m | máscara pronta: nuvem, sombra, água, vegetação... |
| dataMask | Máscara de dado | — | 1 = tem imagem, 0 = sem dado |

## 1.2 Anatomia de uma requisição

Abaixo está uma requisição completa, escrita por extenso.
Leia os comentários: cada bloco responde uma pergunta — **onde, quando, o quê e em que tamanho**.
"""

evalscript_cor_verdadeira = """
//VERSION=3
function setup() {
  return {
    input: ["B02", "B03", "B04"],                              //---> quais bandas o script vai ler
    output: { bands: 3, sampleType: "AUTO" }                   //---> quantas bandas saem e em que formato
  };
}

function evaluatePixel(sample) {                               //---> roda UMA VEZ PARA CADA PIXEL
  return [2.5 * sample.B04, 2.5 * sample.B03, 2.5 * sample.B02];  // R, G, B (x2.5 = clarear)
}
"""

requisicao = {
    "input": {
        "bounds": {                                             # ---> ONDE?
            "bbox": [-50.2990, -9.8974, -50.1054, -9.6984],     # [lon_min, lat_min, lon_max, lat_max]
            "properties": {"crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"},
        },
        "data": [{
            "type": "sentinel-2-l2a",                           # qual satélite/produto
            "dataFilter": {                                     # ---> QUANDO?
                "timeRange": {"from": "2024-07-01T00:00:00Z", "to": "2024-07-31T23:59:59Z"},
                "maxCloudCoverage": 20,                         # ignora cenas com > 20% de nuvem
                "mosaickingOrder": "mostRecent",                # qual cena usar se houver várias (padrão)
            },
        }],
    },
    "output": {"width": 512, "height": 512},                    # TAMANHO da imagem em pixels
    "evalscript": evalscript_cor_verdadeira,                    # ---> O QUÊ? (a receita de cada pixel)
}

garantir_token()
resposta = oauth.post(PROCESS_URL, json=requisicao, headers={"Accept": "image/tiff"})

print("Status HTTP:", resposta.status_code, "(200 = deu certo)")
print("Formato recebido:", resposta.headers.get("Content-Type"))
print(f"Tamanho: {len(resposta.content) / 1e6:.2f} MB")

img = tifffile.imread(io.BytesIO(resposta.content))
print("Array:", img.shape, img.dtype, "| min =", img.min(), "| max =", img.max())

plt.figure(figsize=(8, 8)); plt.imshow(img); plt.title("Rio Araguaia — julho/2024"); plt.axis("off"); plt.show()

"""### E quando dá errado?

A API responde com um código de erro e uma mensagem explicando o motivo. Vamos pedir uma banda que não existe:
"""

import copy

req_errada = copy.deepcopy(requisicao)
req_errada["evalscript"] = evalscript_cor_verdadeira.replace('"B02"', '"B99"')

resposta = oauth.post(PROCESS_URL, json=req_errada, headers={"Accept": "image/tiff"})
print("Status HTTP:", resposta.status_code)   # 400 = erro na requisição
print(resposta.text[:500])
# Outros erros comuns: 401 = token expirou/credencial errada | 429 = muitas requisições (cota)

"""## 1.3 Anatomia do evalscript

O evalscript é um pequeno programa em **JavaScript** que roda no servidor, com duas funções:

* **`setup()`** — roda uma vez: declara quais bandas entram (`input`) e o que sai (`output`).
* **`evaluatePixel(sample)`** — roda **para cada pixel**: recebe os valores das bandas daquele pixel
  (`sample.B04`, `sample.B08`...) e devolve uma lista com os valores de saída.

Para experimentar rápido, a função `pedir()` reaproveita a requisição acima trocando só o que queremos,
e `receita()` monta um evalscript simples a partir das bandas e da linha do `return`:
"""

def pedir(evalscript, de="2024-07-01", ate="2024-07-31", ordem="mostRecent", max_nuvem=20):
    req = copy.deepcopy(requisicao)

    #===========================================================================
    # Substitui cada configuração na requisição do bloco 1.2
    req["evalscript"] = evalscript
    filtro = req["input"]["data"][0]["dataFilter"]
    filtro["timeRange"] = {"from": f"{de}T00:00:00Z", "to": f"{ate}T23:59:59Z"}
    filtro["mosaickingOrder"] = ordem
    filtro["maxCloudCoverage"] = max_nuvem
    #===========================================================================

    garantir_token()
    r = oauth.post(PROCESS_URL, json=req, headers={"Accept": "image/tiff"})
    if r.status_code != 200:
        raise RuntimeError(f"Erro {r.status_code}: {r.text[:300]}")
    return tifffile.imread(io.BytesIO(r.content))

def receita(input_bandas, retorno, n_saida):
    return f"""
//VERSION=3
function setup() {{
  return {{
    input: {input_bandas},
    output: {{ bands: {n_saida}, sampleType: "AUTO" }} }};
}}
function evaluatePixel(sample) {{
  return {retorno};
}}
"""

testes = {
    "Sem realce\n[B04, B03, B02]":
        receita('["B02","B03","B04"]', "[sample.B04, sample.B03, sample.B02]", 3),

    "Realce x2.5\n[2.5*B04, 2.5*B03, 2.5*B02]":
        receita('["B02","B03","B04"]', "[2.5*sample.B04, 2.5*sample.B03, 2.5*sample.B02]", 3),

    "Falsa-cor: vegetação em VERMELHO\n[B08, B04, B03]":
        receita('["B03","B04","B08"]', "[2.5*sample.B08, 2.5*sample.B04, 2.5*sample.B03]", 3),

    "Uma banda só: infravermelho (B08)\nvegetação clara, água escura":
        receita('["B08"]', "[2.5*sample.B08]", 1),
}

print(testes["Falsa-cor: vegetação em VERMELHO\n[B08, B04, B03]"])   # veja o evalscript gerado

fig, axes = plt.subplots(1, 4, figsize=(28, 7))
for ax, (titulo, script) in zip(axes, testes.items()):
    ax.imshow(pedir(script), cmap="gray")    # cmap só é usado quando a imagem tem 1 banda
    ax.set_title(titulo, fontsize=13); ax.axis("off")
plt.tight_layout(); plt.show()

"""## 1.4 `AUTO` × `FLOAT32`: imagem para VER ou dado para CALCULAR?

* **`AUTO`** converte o intervalo 0–1 para 0–255 (inteiro). Ótimo para visualizar, mas **tudo abaixo de 0 vira 0**
  e tudo acima de 1 vira 255.
* **`FLOAT32`** devolve o número de verdade, com casas decimais e sinal.

Índices como NDWI e NDVI vão de **−1 a +1** — com `AUTO` metade da informação se perde.
"""

def ndwi_script(sample_type):
    return f"""
//VERSION=3
function setup() {{
  return {{
    input: ["B03", "B08"],
    output: {{ bands: 1, sampleType: "{sample_type}" }} }};
}}
function evaluatePixel(sample) {{
  return [(sample.B03 - sample.B08) / (sample.B03 + sample.B08)];
}}
"""

ndwi_auto = pedir(ndwi_script("AUTO"))
ndwi_float = pedir(ndwi_script("FLOAT32"))

for nome, arr in [("AUTO", ndwi_auto), ("FLOAT32", ndwi_float)]:
    print(f"{nome:8s} dtype={str(arr.dtype):8s} min={np.nanmin(arr):8.3f}  max={np.nanmax(arr):8.3f}  "
          f"pixels = 0: {np.mean(arr == 0)*100:4.1f}%")

fig, axes = plt.subplots(1, 3, figsize=(24, 7))
axes[0].imshow(ndwi_auto, cmap="gray");  axes[0].set_title("NDWI com AUTO (0–255, negativos viraram 0)")
im = axes[1].imshow(ndwi_float, cmap="RdBu", vmin=-1, vmax=1); axes[1].set_title("NDWI com FLOAT32 (−1 a +1)")
fig.colorbar(im, ax=axes[1], fraction=0.046)
for ax in axes[:2]: ax.axis("off")
axes[2].hist(ndwi_float[np.isfinite(ndwi_float)].ravel(), bins=100, color="#4292c6")
axes[2].axvline(0, color="k", ls="--"); axes[2].set_title("Histograma do NDWI (FLOAT32)")
axes[2].set_xlabel("NDWI  (← terra | água →)")
plt.tight_layout(); plt.show()

"""## 1.5 QUANDO: período, nuvens e qual cena escolher

Num período de 2 meses o satélite passa ~12 vezes. Qual cena a API usa?

* **`maxCloudCoverage`** — descarta cenas com mais nuvem que o limite (% da cena inteira, não só da sua área!)
* **`mosaickingOrder`** — entre as que sobraram: `"mostRecent"` (mais recente, padrão), `"leastRecent"`
  (mais antiga) ou `"leastCC"` (menos nuvem)

Vamos pegar **fev–mar**, época chuvosa e cheia de nuvens:
"""

fig, axes = plt.subplots(1, 2, figsize=(16, 8))
for ax, ordem in zip(axes, ["mostRecent", "leastCC"]):
    ax.imshow(pedir(evalscript_cor_verdadeira, "2024-02-01", "2024-03-31", ordem=ordem, max_nuvem=100))
    ax.set_title(f'mosaickingOrder = "{ordem}"', fontsize=14); ax.axis("off")
plt.tight_layout(); plt.show()

"""## 1.6 ONDE e em que TAMANHO: coordenadas e resolução

**Como pegar as coordenadas:** defina um retângulo no [Bounding Box Tool](https://boundingbox.klokantech.com/) (**Copie as coordenadas em formato CSV**)
ou em [bbox finder](http://bboxfinder.com) e copie os limites. ⚠️ <font color="orange">A API usa **longitude primeiro** (o Google Maps mostra latitude primeiro).</font>⚠️

Em vez de `bbox` também dá para mandar um **polígono** GeoJSON — útil para recortar
exatamente uma fazenda, município ou lago.

**Resolução:** `width`/`height` definem quantos pixels a imagem tem, e portanto quantos metros cada pixel representa.
O Sentinel-2 tem no máximo 10 m; pedir mais pixels que isso não cria detalhe novo, só aumenta o arquivo.
"""

lon_min, lat_min, lon_max, lat_max = requisicao["input"]["bounds"]["bbox"]

#============================| Conversão coordenas -> km |==============================
#longitude = 111,32·cos(lat) (meridianos convergem nos polos)
#latitude ≈ 110,574 (quase constante)
largura_km = (lon_max - lon_min) * 111.32 * np.cos(np.radians((lat_min + lat_max) / 2))
altura_km = (lat_max - lat_min) * 110.574
#=======================================================================================

w, h = requisicao["output"]["width"], requisicao["output"]["height"]

print(f"Área: {largura_km:.1f} km × {altura_km:.1f} km")
print(f"Pedimos {w} × {h} px  →  cada pixel ≈ {largura_km*1000/w:.0f} m × {altura_km*1000/h:.0f} m")
print(f"Para ter 10 m/pixel precisaríamos de {largura_km*100:.0f} × {altura_km*100:.0f} px")
# Repare: largura e altura em km são diferentes, mas pedimos 512 × 512 → a imagem sai levemente esticada.

"""## 1.7 Juntando tudo: a função `baixar()`

Tudo o que vimos — montar o JSON, renovar o token, escolher a cena com menos nuvem, calcular `width`/`height`
a partir da resolução em metros (sem esticar a imagem) e abrir o TIFF — fica guardado numa função só.
Nos exemplos basta dizer **qual receita, onde e quando**.
"""

def tamanho_px(bbox, res_m):
    #Largura/altura em pixels mantendo a proporção real da área (evita imagem esticada).

    # res_m é o parametro que defini a quantidade de metros por pixel que a imagem vai retornar
    # res_m = 10 -> cada pixel terá 10m na imagem (pros: mais preciso os dados, contra: imagem mais pesada)
    # res_m = 60 -> cada pixel terá 60m na imagem (pros: mais leve e economico, contra: menos detalhes)

    lon_min, lat_min, lon_max, lat_max = bbox

    lat_c = np.radians((lat_min + lat_max) / 2)
    largura_m = (lon_max - lon_min) * 111_320 * np.cos(lat_c)
    altura_m = (lat_max - lat_min) * 110_574

    return int(round(largura_m / res_m)), int(round(altura_m / res_m))

def area_pixel_km2(bbox, img):
    #Área aproximada de 1 pixel em km² (para transformar contagem de pixels em área).

    lon_min, lat_min, lon_max, lat_max = bbox

    lat_c = np.radians((lat_min + lat_max) / 2)
    largura_km = (lon_max - lon_min) * 111.32 * np.cos(lat_c)
    altura_km = (lat_max - lat_min) * 110.574

    return largura_km * altura_km / (img.shape[0] * img.shape[1])

def baixar(evalscript, bbox, inicio, fim, res_m=20, max_nuvem=30, ordem="leastCC"):
    #==========================================================================================
    #Baixa um mosaico Sentinel-2 L2A. Datas no formato 'AAAA-MM-DD'.
    #ordem='leastCC' pega a cena com MENOS nuvem do período (o padrão da API é a mais recente).
    #==========================================================================================

    garantir_token()
    largura, altura = tamanho_px(bbox, res_m)
    request = {
        "input": {
            "bounds": {"bbox": list(bbox),
                       "properties": {"crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"}},
            "data": [{
                "type": "sentinel-2-l2a",
                "dataFilter": {
                    "timeRange": {"from": f"{inicio}T00:00:00Z", "to": f"{fim}T23:59:59Z"},
                    "maxCloudCoverage": max_nuvem,
                    "mosaickingOrder": ordem,
                },
            }],
        },
        "output": {"width": largura, "height": altura},
        "evalscript": evalscript,
    }
    r = oauth.post(PROCESS_URL, json=request, headers={"Accept": "image/tiff"})
    if r.status_code != 200:
        raise RuntimeError(f"Erro {r.status_code}: {r.text[:300]}")
    return tifffile.imread(io.BytesIO(r.content))

def realce(rgb, ganho=2.5):
    """Refletância (0–1) -> imagem exibível."""
    return np.clip(np.nan_to_num(rgb) * ganho, 0, 1)

"""# Parte 2 — Exemplos práticos"""

#================================================================================================================================================================================
# ÁREA VARIAVEL — para trocar de rio, mude só >>BBOX e PERIODOS<<.

# Ordem: (lon_min, lat_min, lon_max, lat_max)  ← LONGITUDE PRIMEIRO! (o Google Maps mostra lat, lon) -> recomendação, copie em formato CSV: https://boundingbox.klokantech.com/

# Tamanho máximo: ~50 km de lado com res_m=20 (limite de 2500 px da API); para áreas maiores aumente res_m na função baixar().

# PERIODOS: o 1º deve ser a CHEIA e o último a SECA do rio escolhido (o PERIODO muda de rio para rio).
#================================================================================================================================================================================

BBOX = (-50.2990096611, -9.8973521206, -50.1053756279, -9.6984229431)

PERIODOS = {
    "Cheia (abr–mai)":         ("2024-04-01", "2024-05-31"),
    "Intermediário (jun)":     ("2024-06-01", "2024-06-30"),
    "Seca (jul–ago)":          ("2024-07-01", "2024-08-31"),
}

#===================================================================================
# Um único evalscript devolve TUDO que os exemplos 1–4 precisam:
# bandas 0–2 = RGB, 3 = NDWI, 4 = máscara de nuvem (a partir da banda SCL do L2A)
#===================================================================================

EVAL_AGUA = """
//VERSION=3
function setup() {
  return {
    input: [{ bands: ["B02", "B03", "B04", "B08", "SCL", "dataMask"] }],
    output: { bands: 5, sampleType: "FLOAT32" }
  };
}
function evaluatePixel(s) {
  if (s.dataMask === 0) return [NaN, NaN, NaN, NaN, NaN];
  let ndwi = (s.B03 - s.B08) / (s.B03 + s.B08);
  // SCL: 3 = sombra de nuvem, 8/9 = nuvem, 10 = cirrus
  let nuvem = [3, 8, 9, 10].includes(s.SCL) ? 1 : 0;
  return [s.B04, s.B03, s.B02, ndwi, nuvem];
}
"""

"""## 1. Quanto de água o rio perdeu?

Em vez de só *olhar* o NDWI, vamos **medir**: pixel com NDWI > 0 e sem nuvem = água.
Contando os pixels e multiplicando pela área de cada um, temos km².
"""

cenas = {}
area_agua = {}
for nome, (ini, fim) in PERIODOS.items():
    img = baixar(EVAL_AGUA, BBOX, ini, fim)
    cenas[nome] = img
    ndwi, nuvem = img[..., 3], img[..., 4] == 1
    agua = (ndwi > 0) & ~nuvem
    area_agua[nome] = agua.sum() * area_pixel_km2(BBOX, img)
    print(f"{nome:26s} água = {area_agua[nome]:6.1f} km²   nuvem = {nuvem.mean()*100:4.1f}%")

fig, axes = plt.subplots(1, 4, figsize=(24, 6), gridspec_kw={"width_ratios": [1, 1, 1, 1.2]})
for ax, (nome, img) in zip(axes, cenas.items()):
    ax.imshow(realce(img[..., :3]))
    ax.imshow(np.ma.masked_where(~(img[..., 3] > 0), img[..., 3]), cmap="Blues", vmin=-0.2, vmax=0.6, alpha=0.8)
    ax.set_title(f"{nome}\n{area_agua[nome]:.1f} km² de água", fontsize=13)
    ax.axis("off")

axes[3].bar(area_agua.keys(), area_agua.values(), color=["#08519c", "#4292c6", "#c6dbef"])
axes[3].set_ylabel("Área de água (km²)")
axes[3].tick_params(axis="x", rotation=20)
cheia, seca = list(area_agua.values())[0], list(area_agua.values())[-1]   # 1º período = cheia, último = seca
axes[3].set_title(f"O rio encolheu {100*(cheia-seca)/cheia:.0f}% da cheia para a seca")
plt.tight_layout(); plt.show()

"""## 2. "Água" é uma decisão: limiar interativo

O limiar 0 é uma convenção. Rio com muito sedimento (como o Araguaia na cheia) pode ter NDWI baixo.
Arraste o slider e veja a área mudar — ótimo momento para discutir **incerteza** em sensoriamento remoto.
"""

from ipywidgets import interact, FloatSlider, Dropdown

@interact(periodo=Dropdown(options=list(cenas)),
          limiar=FloatSlider(value=0.0, min=-0.3, max=0.5, step=0.02, continuous_update=False))

def explorar_limiar(periodo, limiar):
    img = cenas[periodo]

    agua = (img[..., 3] > limiar) & (img[..., 4] != 1) # Define qual pixel é agua, a varivel limiar é definido conforme a necessidade
    km2 = agua.sum() * area_pixel_km2(BBOX, img)

    fig, axes = plt.subplots(1, 2, figsize=(16, 8))
    axes[0].imshow(realce(img[..., :3])); axes[0].set_title("RGB")
    axes[1].imshow(agua, cmap="Blues"); axes[1].set_title(f"NDWI > {limiar:.2f}  →  {km2:.1f} km² de água")
    for ax in axes: ax.axis("off")
    plt.show()

"""## 3. Mapa de mudança: cheia × seca

Combinando as duas máscaras de água em uma só imagem com 4 classes (álgebra de mapas):

* **Água permanente** — é água nas duas épocas (o canal principal)
* **Só na cheia** — planície de inundação / bancos de areia que emergem na seca
* **Só na seca** — geralmente ruído, sombra ou lagoas isoladas
* **Terra**
"""

c, s = list(cenas.values())[0], list(cenas.values())[-1]   # 1º período = cheia, último = seca
agua_c = (c[..., 3] > 0) & (c[..., 4] != 1)
agua_s = (s[..., 3] > 0) & (s[..., 4] != 1)
nuvem_qualquer = (c[..., 4] == 1) | (s[..., 4] == 1)

classes = np.zeros(agua_c.shape, dtype=np.uint8)      # 0 = terra
classes[agua_c & agua_s] = 1                           # permanente
classes[agua_c & ~agua_s] = 2                          # só na cheia
classes[~agua_c & agua_s] = 3                          # só na seca
classes[nuvem_qualquer] = 4                            # sem dado (nuvem)

nomes = ["Terra", "Água permanente", "Só na cheia", "Só na seca", "Nuvem"]
cores = ["#f0ead6", "#08306b", "#6baed6", "#e6550d", "#bdbdbd"]
px = area_pixel_km2(BBOX, c)

fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(classes, cmap=mcolors.ListedColormap(cores), vmin=-0.5, vmax=4.5, interpolation="nearest")
ax.legend(handles=[plt.Rectangle((0, 0), 1, 1, color=cor) for cor in cores],
          labels=[f"{n}: {(classes == i).sum() * px:.1f} km²" for i, n in enumerate(nomes)],
          loc="lower right", fontsize=11)
ax.set_title("Mudança da lâmina d'água — Rio Araguaia 2024", fontsize=14); ax.axis("off")
plt.show()

"""### 3b. O mesmo mapa, interativo

Cada classe vira uma **camada separada** sobre uma imagem de satélite de fundo. No painel do canto superior direito
dá para ligar/desligar cada uma (ex.: deixar só "Só na cheia" para ver a planície de inundação),
e também as fotos RGB da cheia e da seca para comparar. Dá zoom, tela cheia e o mapa é salvo como HTML.
"""

import folium
from folium.plugins import Fullscreen, GroupedLayerControl
from folium.map import CustomPane

def mascara_rgba(mask, cor_hex, alpha=200):
    """Máscara booleana -> imagem RGBA: cor onde é True, transparente no resto."""
    r, g, b = mcolors.to_rgb(cor_hex)
    rgba = np.zeros((*mask.shape, 4), dtype=np.uint8)
    rgba[mask] = [int(r*255), int(g*255), int(b*255), alpha]
    return rgba

def rgb_rgba(img):
    """Cena Sentinel-2 -> RGBA para sobrepor no mapa (sem dado = transparente)."""
    rgba = np.zeros((*img.shape[:2], 4), dtype=np.uint8)
    rgba[..., :3] = (realce(img[..., :3]) * 255).astype(np.uint8)
    rgba[..., 3] = np.where(np.isnan(img[..., 0]), 0, 255)
    return rgba

lon_min, lat_min, lon_max, lat_max = BBOX
limites = [[lat_min, lon_min], [lat_max, lon_max]]
nomes_periodos = list(cenas)

# ==== AJUSTES DE TAMANHO ====
LARGURA, ALTURA = 1300, 650   # tamanho do mapa na TELA do notebook, em pixels
REDUZIR = 2                   # reduz o tamanho do arquivo
r = slice(None, None, REDUZIR)
#=============================

figura = folium.Figure(width=LARGURA, height=ALTURA)
mapa = folium.Map(location=[(lat_min + lat_max) / 2, (lon_min + lon_max) / 2], zoom_start=12, tiles=None).add_to(figura)
CustomPane("fotos", z_index=350).add_to(mapa)
folium.TileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                 attr="Esri World Imagery", name="Satélite (fundo)").add_to(mapa)

folium.TileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
                 attr="Esri World Street Map", name="Ruas (fundo)").add_to(mapa)

# Fotos Sentinel-2 (começam escondidas)
fotos = []
for nome, cena in [("Nenhuma", None), (f"📷 RGB {nomes_periodos[0]}", c), (f"📷 RGB {nomes_periodos[-1]}", s)]:
    grupo = folium.FeatureGroup(name=nome, control=False, show=(cena is None))
    if cena is not None:
        folium.raster_layers.ImageOverlay(rgb_rgba(cena[r, r]), bounds=limites, pane="fotos").add_to(grupo)
    grupo.add_to(mapa)
    fotos.append(grupo)

# Uma camada por classe; o nome já funciona como legenda (cor + área)
for i in [1, 2, 3, 4]:                                  # 0 = terra fica transparente
    km2 = (classes == i).sum() * px
    rotulo = f'<span style="color:{cores[i]}; font-size:18px">■</span> {nomes[i]} ({km2:.1f} km²)'
    folium.raster_layers.ImageOverlay(mascara_rgba((classes == i)[r, r], cores[i]), bounds=limites,
                                      name=rotulo, show=(i != 4)).add_to(mapa)

folium.LayerControl(collapsed=False).add_to(mapa)
GroupedLayerControl(groups={"Imagem Sentinel-2": fotos}, exclusive_groups=True, collapsed=False).add_to(mapa)
Fullscreen().add_to(mapa)
mapa.save("mapa_mudanca_cheia_seca.html")
print(f"Arquivo: {os.path.getsize('mapa_mudanca_cheia_seca.html') / 1e6:.1f} MB")
figura

"""## 4. O pulso do rio: 12 meses em um GIF + gráfico

Baixamos um mosaico por mês (com resolução mais baixa, 40 m, para ficar rápido e gastar menos cota)
e, com **o mesmo download**, montamos um timelapse e a curva de área de água ao longo do ano.
"""

from PIL import Image, ImageDraw
from IPython.display import Image as IPImage, display

ANO = 2024 # Define o ano de analise

meses, quadros, km2_mes, nuvem_mes = [], [], [], []
for m in range(1, 13):
    ini, fim = f"{ANO}-{m:02d}-01", f"{ANO}-{m:02d}-{calendar.monthrange(ANO, m)[1]}"

    try:
        img = baixar(EVAL_AGUA, BBOX, ini, fim, res_m=40, max_nuvem=60)
    except RuntimeError as e:
        print(f"{m:02d}: {e}"); continue
    if np.isnan(img[..., 0]).all():
        print(f"{m:02d}: sem cena no período"); continue

    nuvem = img[..., 4] == 1
    agua = (img[..., 3] > 0) & ~nuvem
    meses.append(m)
    km2_mes.append(agua.sum() * area_pixel_km2(BBOX, img))
    nuvem_mes.append(nuvem.mean() * 100)

    quadro = Image.fromarray((realce(img[..., :3]) * 255).astype(np.uint8))
    ImageDraw.Draw(quadro).text((10, 10), f"{calendar.month_abbr[m]} {ANO}  |  água: {km2_mes[-1]:.0f} km²", fill="white")
    quadros.append(quadro)
    print(f"{m:02d}: água {km2_mes[-1]:6.1f} km²  nuvem {nuvem_mes[-1]:4.1f}%")

if not quadros:
    raise RuntimeError("Nenhum mês com imagem — tente aumentar max_nuvem ou mudar o ano.")
quadros[0].save("pulso_araguaia.gif", save_all=True, append_images=quadros[1:], duration=800, loop=0)
display(IPImage(filename="pulso_araguaia.gif"))

fig, ax1 = plt.subplots(figsize=(12, 5))
ax1.plot(meses, km2_mes, "o-", color="#08519c", lw=2, label="Água (km²)")
ax1.set_xticks(range(1, 13), [calendar.month_abbr[m] for m in range(1, 13)])
ax1.set_ylabel("Área de água (km²)")
ax2 = ax1.twinx()
ax2.bar(meses, nuvem_mes, color="gray", alpha=0.3, label="Nuvem (%)")
ax2.set_ylabel("Cobertura de nuvem na cena (%)")
ax1.set_title(f"Pulso de inundação do Araguaia — {ANO}")
fig.legend(loc="upper right"); plt.show()

"""## 5. Caça ao fogo 🔥

No dia 8 de agosto de 2021 ocorreu um enorme incêndio em Eubeia, ilha localizada na Grécia.

Através da imagem obtida no dia conseguimos mostrar duas coisas legais:

1. **Ver através da fumaça** — a composição falsa-cor SWIR (B12, B8A, B04) enxerga através da fumaça,
   mostra o **fogo ativo** em laranja/vermelho e a **cicatriz de queimada** em marrom escuro.
2. **Medir a área queimada** — o índice NBR = (B08 − B12)/(B08 + B12) cai muito depois do fogo.
   A diferença antes − depois (**dNBR**) dá a severidade (classes do USGS).

> As datas antes/depois são um ponto de partida: ajuste conforme a data do fogo que vocês encontrarem.
"""

EVAL_FOGO = """
//VERSION=3
function setup() {
  return {
    input: [{ bands: ["B02", "B03", "B04", "B08", "B8A", "B12", "SCL", "dataMask"] }],
    output: { bands: 8, sampleType: "FLOAT32" }
  };
}
function evaluatePixel(s) {
  if (s.dataMask === 0) return [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN];
  let nbr  = (s.B08 - s.B12) / (s.B08 + s.B12);
  let ndwi = (s.B03 - s.B08) / (s.B03 + s.B08);
  let nuvem = [3, 8, 9, 10].includes(s.SCL) ? 1 : 0;
  // 0-2: RGB | 3-5: falsa-cor SWIR | 6: NBR | 7: NDWI (nuvem vira NaN no NBR)
  return [s.B04, s.B03, s.B02, s.B12, s.B8A, s.B04, nuvem ? NaN : nbr, ndwi];
}
"""

# Parte 1: a mesma cena, "olhos humanos" vs "olhos SWIR"
BBOXfogo = (22.95, 38.70, 23.55, 39.05)

fogo = baixar(EVAL_FOGO, BBOXfogo, "2021-08-08", "2021-08-08", res_m=30, max_nuvem=100)

fig, axes = plt.subplots(1, 2, figsize=(20, 10))
axes[0].imshow(realce(fogo[..., 0:3]));      axes[0].set_title("Cor verdadeira: só fumaça", fontsize=14)
axes[1].imshow(realce(fogo[..., 3:6], 2.0)); axes[1].set_title("Falsa-cor SWIR (B12, B8A, B04): fogo e cicatriz", fontsize=14)
for ax in axes: ax.axis("off")
plt.tight_layout(); plt.show()

# Parte 2: área queimada com dNBR
antes  = baixar(EVAL_FOGO, BBOXfogo, "2021-07-15", "2021-07-31", res_m=30)
depois = baixar(EVAL_FOGO, BBOXfogo, "2021-08-20", "2021-09-10", res_m=30)

dnbr = antes[..., 6] - depois[..., 6]
# Água que secou também muda o NBR -> descartamos pixels que eram água em qualquer data
dnbr[(antes[..., 7] > 0) | (depois[..., 7] > 0)] = np.nan

limites_dnbr = [-np.inf, 0.10, 0.27, 0.44, 0.66, np.inf]                     # classes USGS
nomes_fogo   = ["Não queimado", "Baixa", "Moderada-baixa", "Moderada-alta", "Alta"]
cores_fogo   = ["#e5f5e0", "#fee391", "#fe9929", "#d7301f", "#67000d"]
classe  = np.digitize(dnbr, limites_dnbr[1:-1]).astype(float)
classe[np.isnan(dnbr)] = np.nan

px_ha = area_pixel_km2(BBOXfogo, dnbr) * 100
queimado_ha = np.nansum(dnbr > 0.10) * px_ha

fig, axes = plt.subplots(1, 3, figsize=(27, 9))
axes[0].imshow(realce(antes[..., 3:6], 2.0));  axes[0].set_title("Antes (jul) — SWIR")
axes[1].imshow(realce(depois[..., 3:6], 2.0)); axes[1].set_title("Depois (ago–set) — SWIR")
axes[2].imshow(classe, cmap=mcolors.ListedColormap(cores_fogo), vmin=-0.5, vmax=4.5, interpolation="nearest")
axes[2].set_title(f"Severidade (dNBR) — {queimado_ha:,.0f} ha queimados".replace(",", "."))
axes[2].legend(handles=[plt.Rectangle((0, 0), 1, 1, color=c) for c in cores_fogo],
               labels=[f"{n}: {np.nansum(classe == i) * px_ha:,.0f} ha".replace(",", ".") for i, n in enumerate(nomes_fogo)],
               loc="lower right")
for ax in axes: ax.axis("off")
plt.tight_layout(); plt.show()
print(f"≈ {queimado_ha/100:.1f} km² ≈ {queimado_ha/0.714:,.0f} campos de futebol".replace(",", "."))

"""## 6. O computador descobre as classes sozinho (K-means)

Sem dizer ao algoritmo o que é água, mata ou areia: ele agrupa pixels com "assinatura espectral" parecida.
Depois a classificação de cada grupo é determinado **manualmente** olhando o mapa — é exatamente o fluxo de uma classificação não supervisionada.
"""

from sklearn.cluster import KMeans

EVAL_BANDAS = """
//VERSION=3
function setup() {
  return {
    input: [{ bands: ["B02", "B03", "B04", "B08", "B11", "B12", "dataMask"] }],
    output: { bands: 6, sampleType: "FLOAT32" }
  };
}
function evaluatePixel(s) {
  if (s.dataMask === 0) return [NaN, NaN, NaN, NaN, NaN, NaN];
  return [s.B02, s.B03, s.B04, s.B08, s.B11, s.B12];
}
"""
bandas = baixar(EVAL_BANDAS, BBOX, "2024-07-01", "2024-08-31")
B02, B03, B04, B08, B11, B12 = np.moveaxis(bandas, -1, 0)
ndvi = (B08 - B04) / (B08 + B04)
ndwi = (B03 - B08) / (B03 + B08)

X = np.stack([B02, B03, B04, B08, B11, B12, ndvi, ndwi], axis=-1).reshape(-1, 8)
validos = ~np.isnan(X).any(axis=1)

K = 6   # troque e veja o que acontece!
idx_validos = np.flatnonzero(validos)
amostra = np.random.default_rng(0).choice(idx_validos, min(50_000, idx_validos.size), replace=False)
modelo = KMeans(n_clusters=K, n_init=10, random_state=0).fit(X[amostra])

rotulos = np.full(X.shape[0], -1)
rotulos[validos] = modelo.predict(X[validos])
mapa_kmeans = np.ma.masked_less(rotulos.reshape(B02.shape), 0)

fig, axes = plt.subplots(1, 2, figsize=(20, 10))
axes[0].imshow(realce(np.dstack([B04, B03, B02]))); axes[0].set_title("RGB")
im = axes[1].imshow(mapa_kmeans, cmap="tab10", vmin=-0.5, vmax=9.5, interpolation="nearest")
axes[1].set_title(f"K-means com {K} grupos")
for ax in axes: ax.axis("off")
fig.colorbar(im, ax=axes[1], ticks=range(K), fraction=0.04)
plt.tight_layout(); plt.show()

for k in range(K):
    centro = modelo.cluster_centers_[k]
    print(f"grupo {k}: {np.mean(mapa_kmeans == k)*100:5.1f}% da área | NDVI médio {centro[6]:+.2f} | NDWI médio {centro[7]:+.2f}")

"""## 7. Agora é com vocês: sua cidade

Pegue latitude/longitude no Google Maps (clique com o botão direito → copiar coordenadas),
troque abaixo e rode. Ideias: expansão urbana (compare 2018 × 2024), desmatamento, reservatório secando,
lavoura irrigada (pivôs centrais aparecem como círculos no NDVI!).
"""

def bbox_ao_redor(lat, lon, km=5):
    dlat = km / 110.574
    dlon = km / (111.320 * np.cos(np.radians(lat)))
    return (lon - dlon, lat - dlat, lon + dlon, lat + dlat)

EVAL_NDVI = """
//VERSION=3
function setup() {
  return { input: [{ bands: ["B02", "B03", "B04", "B08", "dataMask"] }],
           output: { bands: 4, sampleType: "FLOAT32" } };
}
function evaluatePixel(s) {
  if (s.dataMask === 0) return [NaN, NaN, NaN, NaN];
  return [s.B04, s.B03, s.B02, (s.B08 - s.B04) / (s.B08 + s.B04)];
}
"""

#===============================================================================
#===============================================================================
LAT, LON = -19.1978, -46.2377          # <------ troque pela sua região
ANOS = [2018, 2024]                    # <------ compare dois anos
bbox_cidade = bbox_ao_redor(LAT, LON, km=5)
#===============================================================================
#===============================================================================

fig, axes = plt.subplots(2, len(ANOS), figsize=(9 * len(ANOS), 18))
for j, ano in enumerate(ANOS):
    img = baixar(EVAL_NDVI, bbox_cidade, f"{ano}-06-01", f"{ano}-08-31", res_m=10)
    ndvi = img[..., 3]
    axes[0, j].imshow(realce(img[..., :3])); axes[0, j].set_title(f"{ano} — RGB")
    im = axes[1, j].imshow(ndvi, cmap="RdYlGn", vmin=-0.2, vmax=0.9)
    axes[1, j].set_title(f"{ano} — NDVI | vegetação densa (>0.6): {np.nanmean(ndvi > 0.6)*100:.0f}%")
for ax in axes.flat: ax.axis("off")
fig.colorbar(im, ax=axes[1, :], orientation="horizontal", fraction=0.03, label="NDVI")
plt.show()